remotes:
  v100:
    type: ec2
    instance-type: p3.2xlarge
    region: us-east-2
    ami: ami-4f62582a
    public-key: ~/.ssh/id_rsa.pub
    connection:
      user: ubuntu
      timeout: 1
    init: |
      set -e
      sudo pip install --pre --upgrade guildai tensorflow-gpu
      guild check
      guild sys shutdown-timer start --timeout 60

  k80:
    type: ec2
    instance-type: p2.xlarge
    region: us-east-2
    ami: ami-4f62582a
    public-key: ~/.ssh/id_rsa.pub
    connection:
      user: ubuntu
      timeout: 1
    init: |
      set -ex
      cat > ~/.bashrc << EOF
        export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64
      EOF
      . ~/.bashrc
      sudo pip install --pre --upgrade guildai tensorflow-gpu
      guild check
      guild sys shutdown-timer start --timeout 60 --su
